algoritmo "EXERCICIO4"
// Função : TUDO MINUSCULO
// Autor : PAULO RICARDO R.A: 25013765-2
// Data : 29/08/2025
// Seção de Declarações
var
  string, menor:caracter
inicio
// Solicite uma string e exiba-a totalmente em maiúsculas.
escreval("Seja bem vindo ao minusculador")
escreval
escreva("Escreva um texto que deva ficar todo em minusculo: ")
leia(string)

menor <- minusc(string)

escreval("Texto corrigido: ", menor)
escreval
fimalgoritmo
