algoritmo "EXERCICIO3"
// Função : TUDO MAIUSCULO
// Autor : PAULO RICARDO R.A: 25013765-2
// Data : 29/08/2025
// Seção de Declarações
var
  string, Maior:caracter
inicio
// Solicite uma string e exiba-a totalmente em maiúsculas.
escreval("Seja bem vindo ao maiusculador")
escreval
escreva("Escreva um texto que deva ficar todo em maiusculo: ")
leia(string)

Maior <- maiusc(string)

escreval("Texto corrigido: ", Maior)
escreval
fimalgoritmo
