algoritmo "EXERCICIO20"
// Função : PRIMEIRO NOME
// Autor : PAULO RICARDO R.A:25013765-2
// Data : 06/09/2025
// Seção de Declarações
var
   nomeCompleto, letra, nome:caracter
   x:inteiro
inicio
//Solicite um nome completo e apresente apenas a primeira palavra.
escreval("Por favor Insira seu nome completo abixo:")
leia(nomeCompleto)

letra<-""

enquanto(asc(letra) <> 32) faca
 para x de 1 ate tam faca
  letra <- copia(nomeCompleto)
  nome <- nome + letra
 fimpara
fimenquanto
fimalgoritmo
