algoritmo "semnome"
// Função : Perimetro Area
// Autor : Paulo Ricardo
// Data : 07/08/2025
// Seção de Declarações 
var
   raio, D, result: real
inicio
// Seção de Comandos 
   escreva("vamos descobrir o perimetro do seu circulo")
   escreval
   escreval
   escreva("insira o valor do raio: ")
   leia(raio)
   
   D <- 2*raio
   result <- 3.1416 * D
   
   escreva("seu resuktado é: ", result)
fimalgoritmo
