algoritmo "semnome"
// Função :  volume cilindro
// Autor : Paulo Ricardo
// Data : 07/08/2025
// Seção de Declarações 
var

 raio, altura: real

inicio
// Seção de Comandos

escreva("vamos decubrir o volume do seu cilindro")
escreval
escreval
escreva("insira o valor do raio: ")
leia(raio)
escreva("insira a altura do cilindro: ")
leia(altura)

escreva("o area do seu cilindro é: ", 3.1416 * (raio*raio) * altura)
fimalgoritmo
