algoritmo "semnome"
// Função : Volume Piramide
// Autor : Paulo Ricardo
// Data : 07/08/2025
// Seção de Declarações 
var
 profund, altura: real
inicio
// Seção de Comandos

escreva("vamos descobrir apresente o volume da sua priamide!")
escreval
escreval
escreva("insira o comprimento da sua piramide: ")
leia(profund)
escreva("insira a altura da sua piramide: ")
leia(altura)

escreva("seu resultado é: ", (profund * profund) * (altura / 3))
fimalgoritmo
