algoritmo "semnome"
// Função : Volume Esfera
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações 
var
  raio: real
inicio
// Seção de Comandos
   escreva("Vamso descobrir o volume de uma esfera: ")
   escreval
   escreva("Insira o raio da esfera: ")
   leia(raio)
   escreval
   escreva("o volume da sua esfera é: ", ((4/3)*3.1416*(raio*raio*raio)):6:2)
fimalgoritmo
