algoritmo "semnome"
// Função : Média
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações
var
  n1, n2, n3: real
  
inicio
// Seção de Comandos
   escreva("Vamso descobrir a média dentre 3 numeros")
   escreval
   escreva("Insira o primeiro numero: ")
   leia(n1)
   escreva("Insira o segundo numero: ")
   leia(n2)
   escreva("Insira o terceiro numero: ")
   leia(n3)
   escreval
   escreva("a sua média é: ", ((n1*n2*n3)/3):6:2)
fimalgoritmo
