algoritmo "semnome"
// Função : Multiplicador
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações
var
  n1, n2, n3: real

inicio
// Seção de Comandos
   escreva("Vamso multiplicar 3 numeros")
   escreval
   escreva("Insira o primeiro numero: ")
   leia(n1)
   escreva("Insira o segundo numero: ")
   leia(n2)
   escreva("Insira o terceiro numero: ")
   leia(n3)
   escreval
   escreva("a multiplicação dos numeros é: ", (n1*n2*n3):6:2)
fimalgoritmo
