algoritmo "semnome"
// Função : Decima parte (parte 2)
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações
var
  n1, n2: real

inicio
// Seção de Comandos
   escreva("Vamos descobrir a decima parte de uma subrtração!")
   escreval
   escreva("Insira o primeiro numero: ")
   leia(n1)
   escreva("Insira o segundo numero: ")
   leia(n2)

   escreva("a decima parte da subtração é: ", ((n1-n2)/10):6:2)
fimalgoritmo
