algoritmo "semnome"
// Função : Decima parte (parte 2)
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações
var
  n1, n2, n3, n4, n5: real

inicio
// Seção de Comandos
   escreva("Vamos descobrir a soma de 5 numeros de sua escolha!")
   escreval
   escreva("Insira um numero: ")
   leia(n1)
   escreva("Insira mais um numero: ")
   leia(n2)
   escreva("Insira mais um numero: ")
   leia(n3)
   escreva("Insira mais um numero: ")
   leia(n4)
   escreva("Insira mais um numero: ")
   leia(n5)

   escreva("a sua soma é: ", (n1+n2+n3+n4+n5):6:2)
fimalgoritmo
