algoritmo "semnome"
// Função : Média idades
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações
var
  name1, name2, name3, name4: caracter
  id1, id2, id3, id4: inteiro

inicio
// Seção de Comandos
   escreva("Vamos descobrir a média da idade de 4 pessoas!")
   escreval
   
   escreva("Insira o nome da primeira pessoa: ")
   leia(name1)
   escreva("Insira a iadde da primeira pessoa: ")
   leia(id1)
   escreva("Insira o nome da segunda pessoa: ")
   leia(name2)
   escreva("Insira a idade da segunda pessoa: ")
   leia(id2)
   escreva("Insira o nome da terceira pessoa: ")
   leia(name3)
   escreva("Insira a idade da terceira pessoa: ")
   leia(id3)
   escreva("Insira o nome da quarta pessoa: ")
   leia(name4)
   escreva("Insira a idade da quarta pessoa: ")
   leia(id4)

   escreval

   escreva("a média é aproximadamente: ", ((id1+id2+id3+id4)/4):3:0)
   
   escreval
fimalgoritmo
