algoritmo "semnome"
// Função : Sorteio e soma
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações 
var
 n1, n2, n3, n4: inteiro
inicio
// Seção de Comandos
   escreva("Bem vindo ao sorteador de 4 numeros e somador!")
   escreval
   escreval
   
 n1 <- randi(100)
 n2 <- randi(100)
 n3 <- randi(100)
 n4 <- randi(100)
 
 escreva("Os números sortidaos foram: ", n1, " ", n2, " ", n3, " ",n4)
 escreval
 escreva(" e a soma deles é: ", n1+n2+n3+n4)
 
 escreval
 escreval

fimalgoritmo
