algoritmo "semnome"
// Função :
// Autor :
// Data : 09/08/2025
// Seção de Declarações
var
 n1, n2, n3: inteiro
inicio
// Seção de Comandos
   escreva("Bem vindo ao sorteador de 4 numeros e somador!")
   escreval
   escreval

 n1 <- randi(100)
 n2 <- randi(100)
 n3 <- randi(100)

 escreva("Os números sortidaos em ordem contraria é: ", n3, " ", n2, " ", n1)
 escreval
 escreva("Os números sortidaos em ordem normal é: ", n1, " ", n2, " ", n3)

 escreval
 escreval
 
 fimalgoritmo
