algoritmo "semnome"
// Função : 2 valores e acrecimo
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações 
var
 n1, n2, vt, prc:real
inicio
// Seção de Comandos 
 escreva("descubra a soma de 2 numero e um acrécimo de 18%")
 
 escreval
 escreval
 
 escreva("insira o 1º numero: ")
 leia(n1)
 escreva("insira o 2º numero: ")
 leia(n2)
 
 escreval
 escreval
 
 vt <- n1+n2
 prc <- vt*0.18
 
 escreva("seu resultado é: ", vt+prc)
 
 escreval
 escreval
fimalgoritmo
