algoritmo "semnome"
// Função :  3 valor soma acrecimos
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações
var
 n1, n2, n3:real
inicio
// Seção de Comandos
 escreva("Cite três valores será apresentado a soma de: 46% do primeiro + 31% do segundo + 14% do terceiro.")

 escreval
 escreval

 escreva("insira o 1º numero: ")
 leia(n1)
 escreva("insira o 2º numero: ")
 leia(n2)
 escreva("insira o 3º numero: ")
 leia(n3)

 escreval
 escreval

 escreva("seu resultado é: ", (n1*0.46) + (n1*0.31) + (n1*0.14))

 escreval
 escreval
fimalgoritmo
