algoritmo "semnome"
// Função : Desconto
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações
var
 v1, v2, vt:real
inicio
// Seção de Comandos
   escreva("bem vindo, insira dois valores para desconto")

   escreva("Por favor insira um valor: ")
   leia(v1)
   escreva("acrecente outro valor: ")
   leia(v2)

   escreval
   escreval

   escreva("o desconto total é: ", (v1+v2) - (v1+v2)*0.58:4:2)

fimalgoritmo
