algoritmo "semnome"
// Função : Somar numeros
// Autor : Paulo Ricardo
// Data : 07/08/2025
// Seção de Declarações 
var
  num1, num2: real
inicio
// Seção de Comandos 
   escreva("     Seja bem vindo ao somador")
   escreval
   escreval
   escreval
   escreva("por favor adicione um numero qualquer: ")
   leia(num1)
   escreva("agora adicione o numero a ser somado ao primeiro: ")
   leia(num2)
   escreval
   escreva("o resultado da sua conta é", num1 + num2)
fimalgoritmo
