algoritmo "semnome"
// Função : area triangulo
// Autor : Paulo Ricardo
// Data : 07/08/2025
// Seção de Declarações 
var
  base, altura: inteiro
inicio
// Seção de Comandos 
escreva("descubra a area de um triângulo!")
escreval
escreval
escreva("por favor me diga a base do seu triangulo: ")
leia(base)
escreva("por favor me diga a altura do seu triangulo: ")
leia(altura)
escreval
escreval
escreva("a area do seu triangulo é: ", (base * altura)/ 2)
fimalgoritmo
