algoritmo "semnome"
// Função : area do circulo
// Autor : Paulo Ricardo
// Data : 07/08/2025
// Seção de Declarações 
var
  raio, area: real
inicio
// Seção de Comandos 
  escreva("vamos descobrir a area do seu circulo!")
  escreval
  escreval
  escreva("por favor me diga o raio do circulo: ")
  leia(raio)
  
  area <- (raio * raio) * 3.1416
  
  escreva("A area do seu circulo é: ", area)
  
fimalgoritmo
