algoritmo "semnome"
// Função : Volume Cone
// Autor : Paulo Ricardo
// Data : 07/08/2025
// Seção de Declarações 
var
 raio, altura: real
inicio
// Seção de Comandos

escreva("vamos descobrir o volume do seu cone: ")
escreval
escreval
escreva("insira o raio do seu cone: ")
leia(raio)
escreva("insira a altura do seu cone: ")
leia(altura)

escreva("seu resultado é: ", (3.1416*(raio*raio)* altura) / 3)
fimalgoritmo
