algoritmo "semnome"
// Função : Volume prisma retangular
// Autor : Paulo Ricardo
// Data : 09/08/2025
// Seção de Declarações 
var
  compBMe, compBMa, altura: real
inicio
// Seção de Comandos 
   escreva("vamos descobreir o volume de um prisma retangular")
   escreval
   escreva("Por favor insira o valor da base menor: ")
   leia(compBMe)
   escreva("agora insira o valor da base maior: ")
   leia(compBMa)
   escreva("Também será necessario a altura: ")
   leia(altura)
   escreval
   escreva("o volume do prisma é: ", compBMe*compBMa*altura)
fimalgoritmo
