algoritmo "EXERCICIO4"
// Função : MEDIADOR DE IDADES
// Autor : PAULO RICARDO R.A 25013765-2
// Data : 09/10/2025
// Seção de Declarações
var
   v: vetor[0..14] de inteiro
   n, x: inteiro
inicio
// Construir um algoritmo que Leia um vetor de 15 elementos, iniciando a partir do
// último elemento (15o).
 escreval
 escreval
 escreval("               Olá Seja bem vindo ao leitor inverso!")

 escreval
 escreval

 escreval("----------------------------------------------------------------------------------")
 escreval
 escreval

 para x de 14 ate 0 passo -1 faca
     escreva("'    insira a ", x +1, "º idade: ")
     leia(n)

     v[x] <- n

 fimpara
 escreval
 escreval

 escreval("----------------------------------------------------------------------------------")


fimalgoritmo
