algoritmo "EXERCICIO_25"
// Função : CONTADOR
// Autor : PAULO RICARDO R.A: 25013765-2
// Data : 17/08/2025
// Seção de Declarações
var
   nome:caracter
   idade, cont:inteiro
inicio
   //Solicitar o nome e a idade de 3 pessoas (utilizando a estrutura PARA).
   escrevaL("Seja bem vindo ao contador de 5 a 20")
   escreval

   para cont de 4 ate 20 faca

    escreval
      escreva(cont+1, " ")
   fimpara
   
   escreval
   escreval
fimalgoritmo
