algoritmo "EXERCICIO30"
// Função : Par de 5 a 50 (para)
// Autor : PAULO RICARDO R.A: 25013765-2
// Data : 23/08/2025
// Seção de Declarações 
var
   num : inteiro
inicio
// Apresentar todos os números ímpares entre 5 e 50, um ao lado do outro (utilizando PARA).

   escreva("Segue numeros: ")

  para num de 5 ate 50 passo 2 faca
   num <- num+1
   escreva(num)
  fimpara
fimalgoritmo
