algoritmo "EXERCICIO_2"
// Função : RECORD SEMANAL
// Autor : PAULO RICARDO R.A: 25013765-2
// Data : 14/08/2025
// Seção de Declarações
var

   pontuacao:real

inicio

  escreva("Olá gamer, seja bem vindo ao seu livro de records!")
  escreval
  escreva("Por favor me diga o valor da sua maior pontuação: ")
  leia(pontuacao)

  SE (pontuacao < 10000) ENTAO
     escreva("Você não atingiu o minimo")
  SENAO
      escreva("Parabéns você é o Detentor do novo recorde!")
  FIMSE
  
fimalgoritmo
