algoritmo "EXERCICIO_15"
// Função : PAR OU IMPAR
// Autor : PAULO RICARDO R.A: 25013765-2
// Data : 16/08/2025
// Seção de Declarações 
var
  num: inteiro
inicio
//Solicitar um número e informar se ele é PAR ou ÍMPAR.

escreva("Seja bem vindo ao identificador de par ou impar numérico")
escreval
escreva("Digite o numero desejado aqui: ")
leia(num)

SE((num%2)=0) ENTAO
  escreval
  escreva("Seu numero é Par")
  escreval
  SENAO
       escreval
       escreval("Seu número é Ímpar")
       escreval
FIMSE
fimalgoritmo
