algoritmo "EXERCICIO_12"
// Função : NUMEROS VALIDOS
// Autor : PAULO RICARDO R.A 25013765-2
// Data : 16/08/2025
// Seção de Declarações 
var
   num: real
inicio
//Solicitar um número entre 10 e 45 e apresentar “Número válido” ou “Número inválido”.
   escreva("Olá!")
   escreval
   escreva("Por favor insira um numero entre 10 e 45 : ")
   leia(num)
   
   SE(num >= 10) E (num <= 45) ENTAO
          escreva("Número valido!")
          SENAO
               escreva("Número invalido!")
   FIMSE
fimalgoritmo
