algoritmo "EXERCICIO_26"
// Função : CONTADOR REVERSO
// Autor : PAULO RICARDO R.A: 25013765-2
// Data : 17/08/2025
// Seção de Declarações
var
   nome:caracter
   idade, cont:inteiro
inicio
   //Solicitar o nome e a idade de 3 pessoas (utilizando a estrutura PARA).
   escrevaL("Seja bem vindo ao contador de 30 a 5")
   escreval
   cont <- 30

   enquanto cont >= 5 faca
      escreva(cont-1, " ")
   fimenquanto

   escreval
   escreval
fimalgoritmo
