
algoritmo "EXERCICIO_1"
// Funcao : APROVACAO PARA PARTICIPACAO DE CAMPEONATO
// Autor : PAULO RICARDO RA: 250.137.65-2
// Data : 14/08/2025
// Secao de Declaracoes 
var

 nickN :caracter
 idade :inteiro
 
inicio

// Q1: Solicitar o nickname e a idade de um jogador. Informar se ele pode participar de um campeonato que exige
//idade mínima de 16 anos.

 escreva("Seja bem vindo Jogador!")
 escreval
 escreva("por favor insira o seu Nick Name: ")
 leia(nickN)
 escreva("Ótimo!")
 escreva("agora me diga a sua idade: ")
 leia(idade)

SE (idade < 16) ENTAO
   ESCREVA("Sinto muito", " ", nickN, " ", "mas você não tem a idade minima para participar")
SENAO
     ESCREVA("Parabéns", " ", nickN, " ", "você foi aprovado para a competindo!")
FIMSE

fimalgoritmo
